services:
  remnashop-db:
    image: postgres:17
    container_name: "remnashop-db"
    hostname: remnashop-db
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=UTC
    
    volumes:
      - remnashop-db-data:/var/lib/postgresql/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  remnashop-redis:
    image: valkey/valkey:9-alpine
    container_name: "remnashop-redis"
    hostname: remnashop-redis
    restart: unless-stopped

    command: [ 
      "--requirepass", "${REDIS_PASSWORD}",
      "--maxmemory", "256mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "300"
    ]

    volumes:
      - remnashop-redis-data:/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    

  remnashop:
    build:
      context: .
      dockerfile: Dockerfile
    image: remnashop:local
    container_name: "remnashop"
    hostname: remnashop
    restart: unless-stopped

    env_file:
      - .env
    environment:
      PYTHONPATH: /opt/remnashop
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop-db:
          condition: service_healthy
        remnashop-redis:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets
      - ./backups:/opt/remnashop/backups
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - remnawave-network
    

  remnashop-taskiq-worker:
    image: remnashop:local
    container_name: "remnashop-taskiq-worker"
    hostname: remnashop-taskiq-worker
    restart: unless-stopped
    command: taskiq worker src.infrastructure.taskiq.worker:worker 
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    env_file:
      - .env
    environment:
      PYTHONPATH: /opt/remnashop
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop:
          condition: service_started
        remnashop-redis:
          condition: service_healthy
        remnashop-db:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets
      - ./backups:/opt/remnashop/backups
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - remnawave-network


  remnashop-taskiq-scheduler:
    image: remnashop:local
    container_name: "remnashop-taskiq-scheduler"
    hostname: remnashop-taskiq-scheduler
    restart: unless-stopped
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    env_file:
      - .env
    environment:
      PYTHONPATH: /opt/remnashop
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop:
          condition: service_started
        remnashop-redis:
          condition: service_healthy
        remnashop-db:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets
      - ./backups:/opt/remnashop/backups
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - remnawave-network


networks:
  remnawave-network:
    name: remnawave-network 
    driver: bridge 
    external: true

volumes:
  remnashop-db-data:
    name: remnashop-db-data
    driver: local
    external: false
    
  remnashop-redis-data:
    name: remnashop-redis-data
    driver: local
    external: false